#DEV

app:
message: This is the property fire fo the ${spring.application.name} for DEV

spring:
datasource:
drive-class-name: org.h2.Driver
url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
username: sa
password: sa

